### ISSUE TITLE
Failed to retrieve directory listing

### ISSUE THREAD

**Issue by Jad3z** [trs/ftp-srv#102]
I'm running this code on Windows and keep getting an error
**Disconnected from server: ECONNABORTED - Connection aborted**
Using FileZilla

```
_Status:	Connecting to 127.0.0.1:21...
Status:	Connection established, waiting for welcome message...
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "\"
Command:	TYPE I
Response:	200 Switch to "binary" transfer mode.
Command:	PASV
Error:	Disconnected from server: ECONNABORTED - Connection aborted
Error:	Failed to retrieve directory listing_
```

```js
var ftp 	= require('ftp-srv');
var fs 		= require('fs')
var path 	= require('path')

var ftpd = new ftp('ftp://0.0.0.0:21', {
	root: path.join(__dirname, 'public'),
        anonymous: true
});

ftpd.on('login', (user, resolve, reject) => {
  resolve({ root: path.join(__dirname, 'public') })
});

ftpd.listen()
```
Is my code wrong?

**Comment by trs** [comment]
Nothing looks particularly wrong about your code.

Are you connecting to the server locally? Or on another computer?

**Comment by schme16** [comment]
I'm getting the same issue, here's the log dump:
```{
	"name": "ftp-srv",
	"hostname": "######", /*anonymized, but was in an XX-00000 format*/
	"pid": 15992,
	"id": "af6fc751-4621-4c4c-8ef3-481940934c11",
	"directive": "LIST",
	"level": 50,
	"err": {
		"message": "operation timed out",
		"name": "TimeoutError",
		"stack": "TimeoutError: operation timed out\n    at afterTimeout (C:\\Users\\U1038447\\Desktop\\playground\\ftp-server\\node_modules\\bluebird\\js\\release\\timers.js:46:19)\n    at Timeout.timeoutTimeout [as _onTimeout] (C:\\Users\\U1038447\\Desktop\\playground\\ftp-server\\node_modules\\bluebird\\js\\release\\timers.js:76:13)\n    at ontimeout (timers.js:427:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)"
	},
	"msg": "operation timed out",
	"time": "2018-07-30T03:12:11.378Z",
	"v": 0
}
```

I'm connecting from the same machine that the server is hosted on, also using Filezilla

**Comment by trs** [comment]
Are you able to post your FTP Client configuration?

**Comment by marcfisher** [comment]
Seeing the same issue.
`const ftpServer = new FtpSrv(`ftp://0.0.0.0:${d.ports[0]}`);
  ftpServer.on('login', (data, resolve, reject) => {
    console.log('login', data);
    //if (data.username !== randomUsername || data.password !== randomPassword) {
    //  reject(new Error('Access Denied.'));
    //}

    resolve({ root: `${process.cwd()}` });
  });

  ftpServer.on('client-error', ({connection, context, error}) => console.log(error));

  ftpServer.listen();
`

In this case the port is 5000. I see the client connecting successfully, but then running a simple `ls` command it times out. The FTP is running on a remote server, connecting from my local computer to it.

**Comment by marcfisher** [comment]
Follow up: Just got to this work. I added "pasv_url": "0.0.0.0" and "pasv_range": "8000-8001", made sure the firewall rule allowed 5000 *AND* 8000-8001, now it is working correctly. Thanks.

**Comment by trs** [comment]
@Jad3z try following what @marcfisher did.
Let me know if you still have problems!
