### ISSUE TITLE
Typescript error: Property 'on' does not exist on type 'FtpConnection'

### ISSUE THREAD

**Issue by HelpfulScripts** [trs/ftp-srv#103]
I am using ftp-srv in a Typescript project. When calling `data.connection.on(...)`
the ts compiler responds with 
`TS2339: Property 'on' does not exist on type 'FtpConnection'`.

A working fix is to update the type declaration in `ftp-srv.d.ts`
from  
`export class FtpConnection {...}`
to 
`export class FtpConnection extends EventEmitter {...}`.
which is also how the actual implementation is defined.

Not sure if this is worth a PR, and also not sure how to add a test for this fix since ftp-srv is not a ts project. Let me know if you would prefer a PR anyway. Otherwise I suggest to incorporate this in the next patch.

**Comment by trs** [comment]
Great catch, easy enough fix: https://github.com/trs/ftp-srv/commit/2a5013447cc1260877442376475e20ffa1b751b2

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/releases/tag/v2.19.3
