### ISSUE TITLE
Fails to install within virtual machine shared folders

### ISSUE THREAD

**Issue by digitalnature** [trs/ftp-srv#113]
Hi,

I'm having issues installing this inside a virtual machine (Ubuntu server), inside a shared folder (from Windows 7).
I think this is a common issue with modules that require compiling binaries.
Something related to symlinks.

I get some ENOENT warnings `tar ENOENT: no such file or directory, lstat...`, then an ENOENT error.

**Comment by trs** [comment]
Not a lot of information for me to work on here, not sure how I can help.
It doesn't seem directly related to this project, might be an environment issue?
If there does end up being an issue with this project, please feel free to comment and expand further.
