### ISSUE TITLE
GnuTLS error -110: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by Johnnyrook777** [trs/ftp-srv#115]
Using RC 3

Im adding TLS using a PFX and passphrase using the following

```
const pfx = fs.readFileSync(config.TLS_PFX_PATH);

ftpOptions.tls = {
   pfx: pfx,
   passphrase: config.TLS_PFX_PASSPHRASE,
 };
```

Then Im getting the following errors when I connect and LIST
Note, Im using FileZilla as an FTP client

> 12:22:24 Status:      	Disconnected from server
> 12:22:24 Status:      	Resolving address of localhost
> 12:22:24 Status:      	Connecting to 127.0.0.1:2021...
> 12:22:24 Status:      	Connection established, waiting for welcome message...
> 12:22:24 Response: 	220 Ready
> 12:22:24 Command:	AUTH TLS
> 12:22:24 Response: 	234 Honored
> 12:22:24 Status:      	Initializing TLS...
> 12:22:24 Status:      	Verifying certificate...
> 12:22:24 Status:      	TLS connection established.
> 12:22:24 Command:	USER lingarddev
> 12:22:24 Response: 	331 Username okay, awaiting password
> 12:22:24 Command:	PASS **********
> 12:22:25 Response: 	230 User logged in, proceed
> 12:22:25 Command:	OPTS UTF8 ON
> 12:22:25 Response: 	200 UTF8 encoding on
> 12:22:25 Command:	PBSZ 0
> 12:22:25 Response: 	200 OK
> 12:22:25 Command:	PROT P
> 12:22:25 Response: 	200 OK
> 12:22:25 Status:      	Logged in
> 12:22:25 Status:      	Retrieving directory listing...
> 12:22:25 Command:	PWD
> 12:22:25 Response: 	257 "/"
> 12:22:25 Command:	TYPE I
> 12:22:25 Response: 	200 Switch to "binary" transfer mode.
> 12:22:25 Command:	PASV
> 12:22:25 Response: 	227 PASV OK (localhost,203,33)
> 12:22:25 Command:	PORT 127,0,0,1,196,177
> 12:22:25 Response: 	200 The requested action has been successfully completed
> 12:22:25 Command:	LIST
> 12:22:25 Response: 	150 File status okay; about to open data connection
> 12:22:25 Response: 	226 Closing data connection
> 12:22:25 Error:        	GnuTLS error -110: The TLS connection was non-properly terminated.
> 12:22:25 Status:      	Server did not properly shut down TLS connection
> 12:22:25 Error:        	Transfer connection interrupted: ECONNABORTED - Connection aborted
> 12:22:25 Error:        	Failed to retrieve directory listing

Any ideas or anyone else having success here?

**Comment by Johnnyrook777** [comment]
#116

**Comment by Johnnyrook777** [comment]
See #116 for fix

**Comment by trs** [comment]
You're correct with this fix. This was caused by destroying the connection before ending it gracefully.
