### ISSUE TITLE
cli: port ignored?

### ISSUE THREAD

**Issue by warpdesign** [trs/ftp-srv#129]
Typing `ftp-srv ftp://0.0.0.0:9876 --root ~/Documents` will print `Unhandled rejection Error: listen EACCES 127.0.0.1:21`: it should listen to port `9876`, not `21`.

**Comment by trs** [comment]
Sorry for this regression, the cli code wasn't updated with the config changes.
I'll fix this asap.

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/pull/130
