### ISSUE TITLE
Anyone using ftp-srv with MacOS

### ISSUE THREAD

**Issue by simonh1000** [trs/ftp-srv#133]
I use this great project to run a server to test my library https://github.com/simonh1000/ftp-deploy
I've recently switched to mac and I can get the server to start and register a login, but it seems to do no more than that - no greeting is received by my client (filezilla) nor any directory listing. I'm looking for ideas on fixing this, and after reading lots of articles that MacOS rather nixed ftp with High Sierra

```

const homeDir =
    require("os").homedir() + "/code/sync/nodejs/ftp-deploy/test/remote/";

const FtpSrv = require("ftp-srv");

const options = {
    greeting: ["test ftp server", homeDir],
    anonymous: true
};

// Using non-standard port
const port = 2121;
const ftpServer = new FtpSrv("ftp://0.0.0.0:" + port, options);

ftpServer.on('login', (data, resolve, reject) => {
    console.log("[login] Connection by", data);
    console.log("[login] Setting home dir to:", homeDir);
    resolve({ root: homeDir });    
});

ftpServer
    .listen()
    .then(() => {
        console.log(`Serving ${homeDir} on port: ${port}`);
    })
    .catch(err => {
        console.log("[error]", err);
    });
```
This is the error I currently get
```
  username: 'anonymous',
  password: '@anonymous' }
[login] Setting home dir to: /code/sync/nodejs/ftp-deploy/test/remote/
{"name":"ftp-srv","hostname":"xxxxx.home","pid":91037,"id":"ebcbfc41-1795-4185-80a8-aed84c5f066c","directive":"LIST","level":50,"err":{"message":"operation timed out","name":"TimeoutError","stack":"TimeoutError: operation timed out\n    at afterTimeout (/code/sync/nodejs/ftp-deploy/node_modules/bluebird/js/release/timers.js:46:19)\n    at Timeout.timeoutTimeout [as _onTimeout] /code/sync/nodejs/ftp-deploy/node_modules/bluebird/js/release/timers.js:76:13)\n    at ontimeout (timers.js:425:11)\n    at tryOnTimeout (timers.js:289:5)\n    at listOnTimeout (timers.js:252:5)\n    at Timer.processTimers (timers.js:212:10)"},"msg":"operation timed out","time":"2018-12-03T20:54:19.594Z","v":0}
```

**Comment by lucasantoiemma** [comment]
Hi simonh1000,
I reproduced your same issue with v2 and 3.0.4 version when the option "pasv_url": "127.0.0.1" is missing.
If you add that property, all works fine.
My tests were performed on Mac 10.13.6 using FileZilla as ftp client.

**Comment by trs** [comment]
@lucasantoiemma Is correct, this is solved by specifying the `pasv_url`.

This is my mistake, I can have this fixed momentaraly. [The docs](https://github.com/trs/ftp-srv#pasv_url) specify the default for `pasv_url` is `127.0.0.1`, but [the code](https://github.com/trs/ftp-srv/blob/master/src/index.js#L21) does not reflect this.

The reason for this is that when an FTP client requests a passive connection using the `PASV` command, the server sends the hostname for the client to connect to in it's response. `ftp-srv` gets this hostname with [either `pasv_url` or the hostname of the `url`](https://github.com/trs/ftp-srv/blob/master/src/index.js#L70). But, if `0.0.0.0` is specified as the url (either `pasv_url` or `url`) it will use a [service to resolve this into the external IP](https://github.com/trs/ftp-srv/blob/master/src/helpers/resolve-host.js#L7) of the server. If the machine isn't set up for external access using this IP it won't work.

I don't think automatically resolving the hostname is a correct way to do this anymore. `0.0.0.0` is a valid hostname to use. Maybe an option `resolve_hostname: false` can bypass this without causing backwards compatibility issues.

But yes, @simonh1000, add a valid `pasv_url` to your options will solve this.

**Comment by simonh1000** [comment]
This hasn't fixed my issues. I was on 2.* and continued not to get any file data back after logging in, even after adding `pasv_url": "127.0.0.1`.

So I tried updating to 3.0.4 and get 
```
{"name":"ftp-srv","hostname":"****","pid":17217,"level":50,"err":{"message":"listen EACCES 127.0.0.1:21","name":"Error","stack":"Error: listen EACCES 127.0.0.1:21\n    at Server.setupListenHandle [as _listen2] (net.js:1269:19)\n    at listenInCluster (net.js:1334:12)\n    at doListen (net.js:1460:7)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"EACCES"},"msg":"[Event] error","time":"2018-12-05T08:13:25.789Z","v":0}
[error] { Error: listen EACCES 127.0.0.1:21
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 21 }
```

Note that my code specifies a non-standard port, specifically to get around EACCES issues with port 21, but this seems to be ignored?

**Comment by trs** [comment]
@simonh1000 3.0.0 changed how options are specified, that's why it was a major change following [semver](https://semver.org/).

The [constructor now only takes the one options object](https://github.com/trs/ftp-srv#new-ftpsrvoptions). You would specify [the `url`](https://github.com/trs/ftp-srv#url) in that object.

**Comment by simonh1000** [comment]
Thanks @trs - should have spotted that. It looks as though it is working now as expected. Thanks so much for the help

**Comment by trs** [comment]
Glad you got it working! Sorry for the confusion between version.
