### ISSUE TITLE
Don't use ipify.org to resolve `0.0.0.0`

### ISSUE THREAD

**Issue by broofa** [trs/ftp-srv#139]
From the README:

> If set to 0.0.0.0, this will automatically resolve to the external IP of the box.

Most people (read, "everyone!") will interpret this as meaning the IP of the host's network interface, but that's not what [actually happens](https://github.com/trs/ftp-srv/blob/master/src/helpers/resolve-host.js#L11).  The current behavior (GETting the IP from ipify.org) is ~~just terrible~~ wrong for several reasons:

* It is not what people expect, so will be confusing ("wtf did this IP come from???")
* It won't work for the majority of cases where the server is behind a firewall with restricted ports.
* Ipify offes no  privacy or quality of service guarantees.  At the risk of being rude, having this as an undisclosed dependency is just irresponsible.

Please get rid of this code and, instead, use something like `[ip.address()](https://www.npmjs.com/package/ip)` to resolve the host's address.

For those users who want to host a public FTP server, I expect a simple README section describing how to use ipify.org or other similar service to obtain the public IP and pass that in as a confugration option should be sufficient. (It also offloads any responsibility you'll otherwise have for dealing with fixing the problems that arise when said services go down.)

**Comment by trs** [comment]
I agree whole heartedly with this.

Passive connections require the server to give the client what IP to use when connecting. I incorrectly assumed using an external service would be the correct way to do this.
Node's net server supports `0.0.0.0` as an unspecified host to listen on, which should just be passed through on listen.

Having the user specify the passive address is also the correct way to do it. That way the user can decide to use some other way (such as a package or ipify) to get this.

Making this change would count be a major version as it is considered breaking.

**Comment by trs** [comment]
Can track changes here: https://github.com/trs/ftp-srv/tree/remove-pasv-url-resolution

**Comment by broofa** [comment]
It would be helpful/easier to review if you linked to a PR rather than to a branch.  Even more helpful if these were separate branches/PRs per issue, but I know that's a nuisance sometimes.

**Comment by trs** [comment]
Released in https://github.com/trs/ftp-srv/releases/tag/v4.0.0
