### ISSUE TITLE
FileSystem override question

### ISSUE THREAD

**Issue by traychotashev** [trs/ftp-srv#148]
Is there a way to override `FileSystem` with virtual as the one provided by https://www.npmjs.com/package/memfs? Will I have to override each of the default `FileSystem` methods with an `fs.*` method to make it work?
Thanks for your response!

**Comment by trs** [comment]
Yes, you'd have to create a new `FileSystem` class that overrides the default method implementations.

Just replacing node's `fs` with `memfs` _may_ just work. You'd have to try it out.

**Comment by traychotashev** [comment]
I'll try those options out, thanks for getting back to me so quickly
