### ISSUE TITLE
Encoding error when transferring binary files (such as photos)

### ISSUE THREAD

**Issue by sin-raben** [trs/ftp-srv#149]
encoding error in binary data transfer (archives,photos, etc.)

in documentation
[doc](https://nodejs.org/api/buffer.html)
> 'latin1' - A way of encoding the Buffer into a one-byte encoded string (as defined by the IANA in RFC1345, page 63, to be the Latin-1 supplement block and C0/C1 control codes).
> 'binary' - Alias for 'latin1'.

I propose to comment out the lines in the file
`this.dataSocket.setEncoding(this.connection.transferType); `

**Comment by trs** [comment]
The encoding type is set by the FTP client using the `TYPE` command.

`TYPE A` will use `ascii`
`TYPE L` will use `binary`

To send binary data you must first send `TYPE and then setup the connection `PASV`/`PORT`

**Comment by sin-raben** [comment]
If you select "TYPE L" or "TYPE I", the data transfer does not become binary because the "setEncoding" method enables text mode of data transfer regardless of arguments. In addition, the argument "binary" is the same as "latin1", that is, the text

**Comment by sin-raben** [comment]
> The encoding type is set by the FTP client using the `TYPE` command.
> 
> `TYPE A` will use `ascii`
> `TYPE L` will use `binary`
> 
> To send binary data you must first send `TYPE L` and then setup the connection (`PASV`/`PORT`).

If you select "TYPE L" or "TYPE I", the data transfer does not become binary because the "setEncoding" method enables text mode of data transfer regardless of arguments. In addition, the argument "binary" is the same as "latin1", that is, the text

**Comment by trs** [comment]
I’m following. The stream is a buffer _until_ [`setEncoding`](https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding) is called.
So we only want to set the encoding if `ascii` is used.

**Comment by trs** [comment]
Should be fixed in: https://github.com/trs/ftp-srv/pull/168
