### ISSUE TITLE
client-error event for transfert (user name undefined)

### ISSUE THREAD

**Issue by purell** [trs/ftp-srv#15]
Hi Stewart,

It's really great that you added the concept of client error, I was just about to contact you about it 2 weeks ago. Without this possibility of capturing errors, the server was crashing when there were firewall issue or anormal connection breaks. Now it seems to works well. Whatever I saw that you modified a lot of code that may helped for crash issue....

While simulating connection failures I noticed that the `client-error` event is triggered twice. So one for the channel command and a second time for the data channel. However, the `connection.userName` property is valid in the channel command event, but for the data channel event it is **undefined**. Is this normal? I think the user name of a command channel connection should be preserved while opening the data channel connection.

Best regards,

**Comment by stewarttylerr** [comment]
Great catch!
Triggering twice may not be the best behaviour, I'll take a look.

As for the event, I was setting the `connection` value incorrectly, it should be:
```js
this.dataSocket.on('error', err => this.server.emit('client-error', {connection: this.connection, context: 'dataSocket', error: err}));
```

This should ensure `connection` is set correctly and `username` will be available.

**Comment by stewarttylerr** [comment]
https://github.com/stewarttylerr/ftp-srv/pull/14/commits/37c3da3a624b82e768fbb2ea7cec98f559f2d897

**Comment by trs** [comment]
Hey @purell, this should be fixed now!
Thanks
