### ISSUE TITLE
Server sent passive reply with unroutable address. Using server address instead.

### ISSUE THREAD

**Issue by devotox** [trs/ftp-srv#157]
The passive reply no longer seems to find the external IP when 0.0.0.0 is used

**Comment by trs** [comment]
Correct, that was removed in the breaking [v4.0.0](https://github.com/trs/ftp-srv/releases/tag/v4.0.0) change.
You need to specify the passive IP using the `pasv_url` option.
If you don't know this you can use a package such as [`public-ip`](https://www.npmjs.com/package/public-ip) to find it using DNS queries.
