### ISSUE TITLE
S3 Backed Filesystem - What to do for invalid methods?

### ISSUE THREAD

**Issue by hongkongkiwi** [trs/ftp-srv#161]
Hi, 

I would like to create an S3 backed virtual file system. 

I was just wondering what to do for methods that cannot be implemented (such as CHMOD). Should I just create an empty implementation and return null?

**Comment by trs** [comment]
Yeah I would create an empty implementation and add the invalid commands to the [`blacklist`](https://github.com/trs/ftp-srv#blacklist) option.

```js
const ftp = new FtpSrv({
  ...
  blacklist: ['CHMOD', ...]
});
```

That way if a client does send that command, they will get a `502 Command blacklisted` response.
