### ISSUE TITLE
Event for when client disconnects

### ISSUE THREAD

**Issue by NeoLegends** [trs/ftp-srv#174]
Hey,

thank you so much for this great library!

We're using it with a virtual file system. In our case we would like to perform some cleanup work once the client disconnects. As far as I can see, the library, however, does not provide an event for this. Am I correct?

If so, treat this as a feature request for one such event. :) With a little guidance I would be happy to file a PR implementing that.

Best Regards!

**Comment by trs** [comment]
Big thanks to @leolabs for implementing this.
