### ISSUE TITLE
Disconnect on 500 errors too drastic

### ISSUE THREAD

**Issue by JonathanRowell** [trs/ftp-srv#189]
The strategy of disconnection on an error which has resulted in a 500 return code is far too drastic because, according to the comment on line 44 in messages.js, it assumes that the FTP client is manually in use.

> The FTP client is "discouraged" from repeating the same exact request.

In fact if the client sends a correct command which is not implemented, here OPTS MLST, the server reports "syntax error" and disconnects. The actual code ought to be 501 according to [RFC 2389](https://tools.ietf.org/html/rfc2389). There is no requirement in any of the RFCs for the server to disconnect. In fact any client **ought** to issue a FEAT command first in order to see if such a feature is available. Unfortunately most don't. And in particular node's [basic-ftp](https://www.npmjs.com/package/basic-ftp) doesn't - it sends on login the following commands and ignores any errors 

> TYPE I, STRU F, OPTS UTF8 ON, OPTS MLST  type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;

The effect is that if one executes client.access({<credentials>}) it logs you in and immediately disconnects.

**Comment by trs** [comment]
Thanks for the issue!
I'm not sure what would actually be causing the server to disconnect here.
Is is possible that the client is disconnecting because the response was wrong?

**Comment by JonathanRowell** [comment]
The server diosconnects on a 500 error. I changed the response to 501 locally to get round the problem.
