### ISSUE TITLE
Issues with passive mode

### ISSUE THREAD

**Issue by JbIPS** [trs/ftp-srv#19]
Hi,

I'm having some issue with the passive mode for any operation that _requires_ it (list, put, mkdir,...)
* with node [FTP client](https://www.npmjs.com/package/ftp), I'm able to execute those operation but within an average of 10 seconds (and sometimes it even drop due to timeouts).
* with a CLI ftp client (Linux default), once I'm connected:
```
230 User logged in, proceed
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227 Entering Passive Mode (X,X,X,X,35,40)
ftp: connect: Invalid argument
ftp>
```
I tried both methods on my FTP server and they work without flaws or timeouts.

I tried to play with the `pasv port range` but without more success and I'm a bit dry on new idea to solve this. Did you experiment this? Have any idea?

Thank you

**Comment by JbIPS** [comment]
Something struck me when writing this issue: the return IP (replaced here by `X,X,X,X`) is not the one I binded but my public IP.  
Returning the right IP fixed the CLI client but not the timeouts 😢

**Comment by trs** [comment]
How are you setting up `ftp-srv`?
Having the URL as something like `ftp://0.0.0.0:21`; all zero's for the hostname designates setting it to your public IP.

**Comment by JbIPS** [comment]
> Having the URL as something like ftp://0.0.0.0:21; all zero's for the hostname designates setting it to your public IP.

Oh, didn't see that sorry. So the returned IP is good but isn't accepted by the client. Does it have something to do with my network?

**Comment by trs** [comment]
If you're accessing the FTP server from an external network, you have to open the ports: the [listening port](https://github.com/trs/ftp-srv#url), and the range of passive ports ([`pasv_range`](https://github.com/trs/ftp-srv#pasv_range)).
How to open them is dependent on your setup.

**Comment by JbIPS** [comment]
No, actually I'm using `ftp-srv` to do some unit tests for my node.js app. So I'm setting up a local server (with `127.0.0.1:9876` now) and query it from my app in the same test run. The server do receive the `PASV` command but that where it seems to end.

**Comment by JbIPS** [comment]
Well for turning this thing upside down, I think the error comes from my node client... I'll inspect that 😉 

Thanks for your help and this lib!

**Comment by JbIPS** [comment]
Just so you know (and for future reference), it **was** me closing the FTP session to soon. Thanks again!

**Comment by trs** [comment]
Great to hear!
