### ISSUE TITLE
Confusion between STAT and LIST

### ISSUE THREAD

**Issue by JbIPS** [trs/ftp-srv#20]
Hi,

It looks like the `STAT` command is actually doing `LIST`'s job. According to [Wikipedia](https://en.wikipedia.org/wiki/List_of_FTP_commands)
* `LIST` returns information of a file or directory
* `STAT` returns information about the server

Looking to your code I saw [stat.js](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stat.js) is returning `FileStat` and `LIST` returns an error when you give a file as path.

To be conform to a FTP server, `STAT` should return the state of the instance and `LIST` should accept a file as argument and do a `fs.stat()` on it.

**Comment by trs** [comment]
Great input.
It looks like I do have a bit of mix up with these commands. For the record, I used http://cr.yp.to/ftp/list.html and http://cr.yp.to/ftp/syst.html as a reference.

Reviewing this and your information, it appears the commands should do the following:

- `LIST`: Return information about a file or directory
- `NLST`: Return contents of a directory
- `STAT`: Return information about the server

How does that look?

**Comment by JbIPS** [comment]
Well, looking at your reference, I think the key is
> The difference between LIST and NLST is that NLST returns a compressed form of the directory, showing only the name of each file, while LIST returns the entire directory. 

So if by "contents of a directory" you means an array of filename it seems perfectly valid to me 👍

**Comment by trs** [comment]
These commands will be updated to reflect the RFC documentation.

#### `LIST`
[rfc959](https://tools.ietf.org/html/rfc959) - Page 31 - 32

            This command causes a list to be sent from the server to the
            passive DTP.  If the pathname specifies a directory or other
            group of files, the server should transfer a list of files
            in the specified directory.  If the pathname specifies a
            file then the server should send current information on the
            file.  A null argument implies the user's current working or
            default directory.  The data transfer is over the data
            connection in type ASCII or type EBCDIC.  (The user must
            ensure that the TYPE is appropriately ASCII or EBCDIC).
            Since the information on a file may vary widely from system
            to system, this information may be hard to use automatically
            in a program, but may be quite useful to a human user.

**Changes to be made:**
- Support a file as an argument, send information on that file.

#### `NLST`
[rfc959](https://tools.ietf.org/html/rfc959) - Page 32

            This command causes a directory listing to be sent from
            server to user site.  The pathname should specify a
            directory or other system-specific file group descriptor; a
            null argument implies the current directory.  The server
            will return a stream of names of files and no other
            information.  The data will be transferred in ASCII or
            EBCDIC type over the data connection as valid pathname
            strings separated by <CRLF> or <NL>.  (Again the user must
            ensure that the TYPE is correct.)  This command is intended
            to return information that can be used by a program to
            further process the files automatically.  For example, in
            the implementation of a "multiple get" function.

**Changes to be made:**
- None

#### `STAT`
[rfc959](https://tools.ietf.org/html/rfc959) - Page 32 - 33

            This command shall cause a status response to be sent over
            the control connection in the form of a reply.  The command
            may be sent during a file transfer (along with the Telnet IP
            and Synch signals--see the Section on FTP Commands) in which
            case the server will respond with the status of the
            operation in progress, or it may be sent between file
            transfers.  In the latter case, the command may have an
            argument field.  If the argument is a pathname, the command
            is analogous to the "list" command except that data shall be
            transferred over the control connection.  If a partial
            pathname is given, the server may respond with a list of
            file names or attributes associated with that specification.
            If no argument is given, the server should return general
            status information about the server FTP process.  This
            should include current values of all transfer parameters and
            the status of connections.

**Changes to be made:**
- Eventually, I would like to support file transfer status and more information about the server

**Comment by JbIPS** [comment]
Perfect!

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/pull/21
