### ISSUE TITLE
Overriding FileSystem

### ISSUE THREAD

**Issue by stvnmoon** [trs/ftp-srv#22]
I'm not a node expert and am struggling with how to override the filesystem. I have ftp-srv working fine using the default setup, even running in a docker container.

My application requires receiving a CSV file, converting it to JSON (potentially into a pg database) and send some data to a different REST API. My plan was to override ftp-srv file system based on a login and process the csv file stream into a json file so that I can reply to the ftp client immediately if there are any format errors. If conversion is successful I would then trigger a different process to push data to the REST API while retaining the original file and the JSON version. I may even move this to be done 100% in-memory. Unfortunately, having the third party write directly to our REST API is not an option because they only support FTP transfers. There are other ways I could do this, but there are other benefits for me in this approach that are outside of the scope of this problem.

The documentation on this is light so the best I've been able to determine is to pass a custom FileSystem object with the response from the login event (login event from your test `start.js`)
``` javascript
server.on('login', ({connection, username, password}, resolve, reject) => {
  if ((username === 'test' || username === 'testdb') && password === 'test' || username === 'anonymous') {
    if (username === 'testdb') {
      var root = '/code/data';
      var cwd = '/';
      return resolve({root: root, cwd: cwd, fs: new DbFileSystem(connection, {root: root, cwd: cwd}) });
    } else {
      return resolve({ root: '/code/data', cwd: '/' });
    }
  } else {
    reject('Bad username or password');
  }
});
```
First of all, is this the right approach?

I then assumed the next step is to extend the FileSystem class:
``` javascript
const { FileSystem } = require('ftp-srv/fs');
const csv = require('csvtojson')


class DbFileSystem extends FileSystem {
  constructor(connection, { root, cwd } = {}) {
    super(connection, root, cwd);
  }

  write(fileName, {append = false} = {}) {
    const {fsPath} = this._resolvePath(fileName);
    const stream = syncFs.createWriteStream(fsPath, {flags: !append ? 'w+' : 'a+'});
    stream.on('error', () => fs.unlink(fsPath));
    
    // conceptually, this is what I want to do while the stream is being received 
    // (I know this function is the wrong place for this code)
    csv()
    .fromStream(csvReadStream)
    .on('csv',(csvRow)=>{
      // csvRow is an array
    })
    .on('done',(error)=>{
    
    })
    
    return stream;
  }
}

module.exports = DbFileSystem;
```
Perhaps this is wrong, but now I don't know where to go next because write only creates a new `stream.Writable` and stream is handled asynchrounously in the `src/commands/registration/stor.js: handler`. Do I also need to override the `STOR` directive? 😕 

Thanks

**Comment by trs** [comment]
You're on the right track, sorry the docs are sparse on the file system override!

So when user `testdb` logs in, they are now using your extended `DbFileSystem` class, all other users will use the regular file system. Looking good.

So yes, `write` returns a stream, the [`stor`](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L19) handler then replies to the client depending on if that stream finishes or errors out.

Once the `stor` handler receives a stream, it starts writing the data it's getting from the client onto that stream. So in your `write` function, you can listen to [events](https://nodejs.org/api/stream.html#stream_class_stream_writable) and process it accordingly.

If you listen to the data event, you can write the data to a string, once the stream has emitted `finish` you can parse the string and processes it as you desire.

Calling [`destroy()`](https://nodejs.org/api/stream.html#stream_writable_destroy_error) on your stream will cause an [error to be sent](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L21) to the client.
Right now, once the client finishes sending its data to the stream, it emits `finish` on the stream. This would cause the server to reply with "[all good](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L23)" to the client. So sending errors during processing may be an issue. This is something I can look into.


Here's an example, it writes a file and uploads it to S3 once complete:

```
write(fileName) {
  const localFile = `/tmp/${fileName}`;
  const stream = fs.createWriteStream(localFile);

  stream.once('finish', () => {
    when.promise((resolve, reject) => {
      const uploader = this.s3.uploadFile({ // Initialized S3 instance (https://www.npmjs.com/package/s3)
        localFile,
        s3Params: { Key: fileName }
      });
      uploader.on('error', reject);
      uploader.on('end', resolve);
    })
    .then(() => console.log('uploaded file'))
  });

  return stream;
}
```

**Comment by stvnmoon** [comment]
Thanks for the quick response. Your description and example are very helpful. I should be able to get going with this. 

Cheers

**Comment by stvnmoon** [comment]
Regarding the errors during processing; I'm not really sure how practical it is because the csv parser will require complete lines and it's unlikely the stor chunks will be aligned to line endings. Is it possible to have an event like 'pre-finish' where the stream is finished and the file written but the client reply has not been sent, then use it to process and give a success/fail with a message for the stor handler to use to reply to client? Or, a callback/promise instead of a event? Perhaps these ideas are wrong-headed...

**Comment by trs** [comment]
So taking a look at the node [stream documentation](https://nodejs.org/api/stream.html#stream_class_stream_writable), I can leverage the `close` and `finish` events.
Once the dataSocket has finished writing to the provided stream, it will emit the `close` event.
By default, close will call `end()` which will emit the `finish` event.

If you override it, you can listen to the `close` event and do your parsing there. If any errors occur you can `emit` them on the stream. If everything is good, you can finish by calling `end()` on the stream.

See: https://github.com/trs/ftp-srv/pull/23

So an updated example now:
```js
write(fileName) {
  const localFile = `/tmp/${fileName}`;
  const stream = fs.createWriteStream(localFile);

  stream.once('close', () => {
    when.promise((resolve, reject) => {
      const uploader = this.s3.uploadFile({ // Initialized S3 instance (https://www.npmjs.com/package/s3)
        localFile,
        s3Params: { Key: fileName }
      });
      uploader.on('error', reject);
      uploader.on('end', resolve);
    })
    .then(() => stream.end())
    .catch(err => stream.emit('error', err));
  });

  return stream;
}
```

**Comment by stvnmoon** [comment]
Brilliant. I think this will work. Thanks so much. I'll keep you updated.

**Comment by stvnmoon** [comment]
@trs just and update, this works perfectly. I am able to do everything I need. Thanks

**Comment by Rishabhqleverlabs** [comment]
Hi @imoon could you please paste your final code, I am also trying to do a similar thing.
Thanks
