### ISSUE TITLE
Allow only part of the FS to be overwritten

### ISSUE THREAD

**Issue by JbIPS** [trs/ftp-srv#24]
What would you think to let the user overwrite only a part of the FS ? Use case: I only want to implement the `list()` method so it would return the `.` folder as well.

What I would like to do:
```javascript
    srv.on('login', ({connection, username, password}, resolve, reject) => {
      resolve({fs: {
        list: function(path) {...}
     });
   });
```

Basically, this means operating a `merge` [here](https://github.com/trs/ftp-srv/blob/88f02cd4985f8e7b7896470ef0743067208e6169/src/connection.js#L70) instead of an `OR`.

What do you think of that? If you're ok with it I can write a PR for that.

**Comment by trs** [comment]
This can be done by `extends`-ing the class!

```js
const FileSystem = require('./fs.js');

class MyFileSystem extends FileSystem {
  constructor() {
     super(...arguments);
  }

  list(path) {
     // new list function
  }
}
```

```js
...
resolve({ fs: new MyFileSystem(...) });
...
```

This way, all methods will be the same as the vanilla file system except for your new list function.

**Comment by JbIPS** [comment]
You're right, but if I'm not mistaken, this class is not exposed.

**Comment by trs** [comment]
That would be an issue, wouldn't it?

I will expose that, it will make extending the file system much easier!

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/pull/25

**Comment by JbIPS** [comment]
Thanks :+1:

**Comment by stvnmoon** [comment]
@trs thanks indeed! 🙌 I was wondering why I couldn't extend.
