### ISSUE TITLE
File transfer using FileZilla failed

### ISSUE THREAD

**Issue by SiddharthMishraPersonal** [trs/ftp-srv#27]
I have used "https://github.com/trs/ftp-srv/blob/master/test/start.js" code to create an FTP Server on localhost. It shows the directory listing correctly in FileZilla. But when I try to transfer a file it fails at STOR directive by throwing Timeout error.

Am I missing anything here?

`{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"level":10,"msg":"[ 'STOR test.txt' ]","time":"2017-06-13T16:48:18.667Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"directive":"STOR","level":10,"command":{"directive":"STOR","arg":"test.txt","raw":"STOR test.txt"},"msg":"Handle command","time":"2017-06-13T16:48:18.668Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"level":20,"port":1024,"msg":"Passive connection fulfilled.","time":"2017-06-13T16:48:18.671Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"level":20,"msg":"Passive connection closed","time":"2017-06-13T16:48:18.677Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"level":20,"msg":"Passive server closed","time":"2017-06-13T16:48:18.677Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"directive":"STOR","level":50,"err":{"message":"timed out after 5000ms","name":"TimeoutError","stack":"TimeoutError: timed out after 5000ms\n    at onTimeout (/Users/siddharth.mishra/GitlabRepos/analytics-api-ftp-server/node_modules/when/lib/decorators/timed.js:69:7)\n    at Timeout._onTimeout (/Users/siddharth.mishra/GitlabRepos/analytics-api-ftp-server/node_modules/when/lib/decorators/timed.js:13:4)\n    at ontimeout (timers.js:380:14)\n    at tryOnTimeout (timers.js:244:5)\n    at Timer.listOnTimeout (timers.js:214:5)"},"msg":"timed out after 5000ms","time":"2017-06-13T16:48:23.677Z","v":0}
{"name":"test","hostname":"SiddharthsMBP2","pid":2623,"id":"64bd4903-a7b2-4ee6-bab7-b8405605ba37","ip":null,"level":10,"port":8880,"packet":"425 No connection established","msg":"Reply","time":"2017-06-13T16:48:23.677Z","v":0}
`

**Comment by trs** [comment]
Can you post your FtpSrv setup code?

**Comment by trs** [comment]
Taking a look at the logs you posted, the passive connection is resolved and closed right after you send the first `STOR` command, then you send another `STOR` command right after. This causes a timeout error since no passive connection was obtained. You have to setup a passive connection via `PASV` before using any commands that require it (such as `STOR`).

You said it is with FileZilla, so I assume you're not just sending commands yourself, so I'm thinking it's a setup with either the server or client. I can only do more if I see how you've set it up.

**Comment by SiddharthMishraPersonal** [comment]
@trs Sorry for the late reply. It seems I screwed up with some basic settings for getting current working directory and root in FTP setup. It is working now for me. Thanks for your inputs though.

**Comment by SiddharthMishraPersonal** [comment]
Marking this issue closed.
