### ISSUE TITLE
Retrieving file with accent failing.

### ISSUE THREAD

**Issue by purell** [trs/ftp-srv#28]
Hi,

If we try to retrieve a file having accent in its name, the server returns 550 ENOENT. Linux or Windows.

Here is a screen shot of the problem :

![image](https://user-images.githubusercontent.com/7946730/27358002-9b4ae4dc-55e2-11e7-85fa-442e6809153b.png)

Best regards,

**Comment by trs** [comment]
Great catch.
Turns out I was doing encoding and transfer type incorrectly.

The command socket should be using `UTF8`, the data socket uses whatever encoding is set by `TYPE` (default `binary`)

https://github.com/trs/ftp-srv/pull/29

**Comment by trs** [comment]
This should work now with [`v2.9.2`](https://github.com/trs/ftp-srv/releases/tag/v2.9.2). Can you confirm?

**Comment by purell** [comment]
Hi Tyler,

I installed the v2.9.2. Now I'm able to retrieve the folder but the name displayed seems to have an incorrect encoding.

Here in the screen shot you see Filezilla showing `RÃ©mi` and in the Window File Explorer you see `Rémi`.

![image](https://user-images.githubusercontent.com/7946730/27539661-566f971e-5a4b-11e7-88aa-be2e6edfd8ce.png)

**Comment by trs** [comment]
@purell If you force UTF-8 encoding inside FileZilla it should work as expected.

![image](https://user-images.githubusercontent.com/15315657/27546775-03045a82-5a51-11e7-8971-645d42845c72.png)

I'm looking into how to show that the server supports UTF-8 without forcing it client side.

**Comment by purell** [comment]
Maybe this : https://tools.ietf.org/html/draft-ietf-ftpext-utf-8-option-00#page-5

**Comment by trs** [comment]
It doesn't seem that FileZilla ever sends an `OPTS` command.

**Comment by purell** [comment]
I did a test connecting to an IIS FTP server on my domaine and here is the log of FileZilla Client

```
Status:	Connection established, waiting for welcome message...
Trace:	CFtpControlSocket::OnReceive()
Response:	220 Microsoft FTP Service
Trace:	CFtpControlSocket::SendNextCommand()
Command:	AUTH TLS
Trace:	CFtpControlSocket::OnReceive()
Response:	234 AUTH command ok. Expecting TLS Negotiation.
Status:	Initializing TLS...
Trace:	CTlsSocket::Handshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	TLS Handshake successful
Trace:	Protocol: TLS1.0, Key exchange: RSA, Cipher: AES-128-CBC, MAC: SHA1
Status:	Verifying certificate...
Status:	TLS connection established.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	USER ***
Trace:	CFtpControlSocket::OnReceive()
Response:	331 Password required for ***.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PASS *********
Trace:	CFtpControlSocket::OnReceive()
Response:	230 User logged in.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	OPTS UTF8 ON
Trace:	CFtpControlSocket::OnReceive()
Response:	200 OPTS UTF8 command successful - UTF8 encoding now ON.
```

From what I've read here, FileZilla client is aware of UTF-8 (https://wiki.filezilla-project.org/Character_Encoding)


Maybe you should try returning `UTF=8` in the `FEAT`command ?
Ref : https://forum.filezilla-project.org/viewtopic.php?t=19683

**Comment by trs** [comment]
I have `UTF8` in the list of FEATures: https://github.com/trs/ftp-srv/blob/master/src/commands/registration/feat.js#L12

FileZilla doesn't seem to even send the `FEAT` command when connecting to a server.
I added the `OPTS UTF8` handler, but again FileZilla doesn't send that.

It's somehow detecting the character set, and I need to figure out how.

**Comment by trs** [comment]
Looks like I'm sending the `FEAT` response incorrectly.

After fixing it, if I do not specify the transfer type or specify active in FileZilla, it correctly sends `OPTS UTF8 ON`.
If I specify the transfer type as passive, it does not send `OPTS UTF8 ON`.

**Comment by purell** [comment]
Active VS Passive transfer VS UTF-8 ? That's weird ! I don't understand how they are related.

**Comment by trs** [comment]
I've released https://github.com/trs/ftp-srv/pull/30, it should fix this issue for the most part.
I'm still having FileZilla not send `OPTS UTF8 ON` if I specify the transfer type as "passive".
Using "default" or "active" works as expected.

Thanks for the issue!
