### ISSUE TITLE
Occur error when connect ftp on Chrome

### ISSUE THREAD

**Issue by SejoongDeJang** [trs/ftp-srv#31]
I ran ftp server  on Unbutu 12.04.
And I connected through chrome browser I got error.
Both firefox and ie were work fine.

Here is my server code
`const os = require('os');
const FtpSrv = require('ftp-srv');
const bunyan = require('bunyan');

const log = bunyan.createLogger({ name: '97' });
log.level('trace');

const server = new FtpSrv('ftp://168.219.244.97:21', {
    anonymous: 'sillyrabbit',
    log: log,
    pasv_range: 8881,
    greeting: ['Welcome', 'to', 'the', 'jungle!'],
    tls: {
        key: `${process.cwd()}/files.mysite.key`,
        csr: `${process.cwd()}/files.mysite.csr`,
        crt: `${process.cwd()}/files.mysite.crt`
    }
});

server.on('login', (data, resolve, reject) => {
    if (data.username === 'anonymous') {

        resolve({
            root: '/home6/common/'
        });
    } else {
        reject();
    }
});

server.on('client-error', ({ connection, context, error }) => {
    console.log(context);
    console.log(error);
});

server.on('error', (err) => {
    console.log(err);
});

server.on('uncaughtException', (err) => {
    console.log(err);
})
server.listen();`

And followed log is error when I connect through Chrome.
`{"name":"97","hostname":"VDBS1485","pid":15878,"id":"99231d2a-68a7-4bd9-b3c6-b636384702ab","ip":null,"level":10,"msg":"[ 'LIST -l' ]","time":"2017-07-05T04:35:28.656Z","v":0}
{"name":"97","hostname":"VDBS1485","pid":15878,"id":"99231d2a-68a7-4bd9-b3c6-b636384702ab","ip":null,"directive":"LIST","level":10,"command":{"directive":"LIST","arg":"-l","raw":"LIST -l"},"msg":"Handle command","time":"2017-07-05T04:35:28.656Z","v":0}
{"name":"97","hostname":"VDBS1485","pid":15878,"id":"99231d2a-68a7-4bd9-b3c6-b636384702ab","ip":null,"directive":"LIST","level":50,"err":{"message":"ENOENT: no such file or directory, stat '/home6/common/-l'","name":"Error","stack":"Error: ENOENT: no such file or directory, stat '/home6/common/-l'\n    at Error (native)","code":"ENOENT"},"msg":"ENOENT: no such file or directory, stat '/home6/common/-l'","time":"2017-07-05T04:35:28.657Z","v":0}
{"name":"97","hostname":"VDBS1485","pid":15878,"id":"99231d2a-68a7-4bd9-b3c6-b636384702ab","ip":null,"level":10,"port":21,"encoding":"utf8","packet":"451 ENOENT: no such file or directory, stat '/home6/common/-l'","msg":"Reply","time":"2017-07-05T04:35:28.657Z","v":0}
`

**Comment by trs** [comment]
Looks like you're passing in an argument (`-l`) to the `LIST` command.
Currently, options are not supported, but I'll see if I can add them.

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/pull/32

**Comment by SejoongDeJang** [comment]
@trs It work well!! :+1:
