### ISSUE TITLE
STOR operation attempts to destroy stream instead of socket

### ISSUE THREAD

**Issue by rdominy** [trs/ftp-srv#35]
In the stor.js file, line 33:

      .finally(() => when.try(stream.destroy.bind(stream)));

This line attempts to call destroy on the writable stream (the class stream.Writable has no destroy method) returned from the FileSystem.write method.  I suspect this should be against the data socket like so:

      .finally(() => when.try(dataSocket.destroy.bind(dataSocket)));

Edit: To clarify I'm using a Duplex PassThrough stream for which destroy is not defined.  I see now that the Writable stream has a non-public destroy method.  It doesn't look like the Duplex stream implements that until an update added in May (not in the version I have).  

If this is intended to called be on the writable stream, I can shim it for the time being.

**Comment by trs** [comment]
The `stream` is what is meant to be destroyed as the `dataSocket` is ended by calling `this.connector.end()` [here](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L44).

The reason I added the stream destroy was to clean up in the event of an error, I'm not sure if it is completely necessary or not.

[I've added a check for the existence of `destroy` for these cases.](https://github.com/trs/ftp-srv/pull/36/files#diff-f56c7d8736f922a799c5649a00762bedR29)
