### ISSUE TITLE
Crash when aborting download

### ISSUE THREAD

**Issue by purell** [trs/ftp-srv#39]
Hi,

I connect to the server using FileZilla and then download about 100 files of (1-2K each). On half of the transfert I removed all remaining items (~50 files) from the download queue of FileZilla. After what, Filezilla seems to detect a connection break. I tried reconnecting but the server does no longer listen on that port.

```
netstat -anp | grep 21
```
Give nothing, ftp-srv crashed.

I then look on the console and then I saw this error, maybe it will help you. 

```
Cannot read property 'write' of null","name":"TypeError","stack":"TypeError: Cannot read property 'write' of null\n    
at ReadStream.stream.on.data (/root/xxx/node_modules/ftp-srv/src/commands/registration/retr.js:18:56)\n    
at emitOne (events.js:96:13)\n    
at ReadStream.emit (events.js:188:7)\n    
at readableAddChunk (_stream_readable.js:176:18)\n    
at onread (fs.js:2018:12)\n    
at FSReqWrap.wrapper [as oncomplete] (fs.js:683:17)
```

I'm using the latest version : **ftp-srv : 2.11.2**

**Comment by trs** [comment]
Thanks for the issue!

[This PR](https://github.com/trs/ftp-srv/pull/40) should ensure the socket exists before trying to write to it.

**Comment by purell** [comment]
Thanks you :)
