### ISSUE TITLE
Problem with outside visibility

### ISSUE THREAD

**Issue by alexandre1985** [trs/ftp-srv#42]
I'm using this ftp server on my android box using Termux.
Using the LAN, my ftp server works great. But when I'm accessing from outside of my LAN it doesn't work. I got the message Socket couldn't write, but all my permissions of files and directories are 777, and I think that I got an 5000ms timeout error once in the past.
One thing to note is that my `ls` it is not on `/bin/ls` but it is on `/data/data/com.termux/files/usr/bin/ls`.
So here it is my program:
```
process.chdir(__dirname);

const FtpSvr = require('ftp-srv');
const ftpServer = new FtpSvr('ftp://0.0.0.0:3000', {anonymous: true, pasv_range: 8000});

ftpServer.on('login', ({connection, username, password}, resolve, reject) => {
	if(username === 'daniel' && password === 'ola') {
		resolve({root: './data/'});
	} else {
		resolve({root: './data/anonymous'});
	}
});

ftpServer.listen();
```
and here is an image of an outside test of my server using [https://ftptest.net/](https://ftptest.net/):
![deepinscreenshot_chromium_20171020151739](https://user-images.githubusercontent.com/5586308/31825351-e163b242-b5a9-11e7-9bfd-b7ac840527f4.png)
Can someone help me?

**Comment by trs** [comment]
It appears the FTP server is timing out waiting for a passive connection (https://github.com/trs/ftp-srv/blob/master/src/commands/registration/list.js#L43). If a connection is not established, you will get the error `425 No connection established`.

Have you forwarded the `pasv_range` ports? With your option, it will attempt to use ports `8000` - `65535`.

**Comment by alexandre1985** [comment]
I forwarded the `pasv_range` ports and it solved. Thank you
