### ISSUE TITLE
ftp-srv.d.ts not included with npm install

### ISSUE THREAD

**Issue by aam-dmeadows** [trs/ftp-srv#43]
Trying to use ftp-srv with TypeScript. Whenever I do an npm install the type definition is not included. I've been install ftp-srv v2.11.3

**Comment by trs** [comment]
As far as I'm aware, they should be available: https://github.com/trs/ftp-srv/blob/master/package.json#L44

This may be an issue with your setup.

**Comment by aam-dmeadows** [comment]
I agree they should be, but running `npm install --save ftp-srv` does not include them in the install. I was able to reproduce this quickly by creating an empty directory and running install. All that is included is

- LICENSE
- README.md
- ftp-srv.js
- package.json
- src (which also does not include the type definition)

**Comment by trs** [comment]
I figured npm would be smart and include that file with the `types` property.

This PR should fix that by explicitly including it: https://github.com/trs/ftp-srv/pull/44

**Comment by aam-dmeadows** [comment]
Thanks! 👍
