### ISSUE TITLE
TLS on ftp

### ISSUE THREAD

**Issue by alexandre1985** [trs/ftp-srv#45]
Can someone give me an code example how to set up tls on ftp? Do I need the node tls package?

**Comment by trs** [comment]
`ftp-srv` handles TLS for you. You just have to provide the keys and certs, etc.

Check out the this test file for an example: https://github.com/trs/ftp-srv/blob/master/test/index.spec.js#L25

More documentation on this can be found here: https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by alexandre1985** [comment]
Thanks. I think I have successfully configure explicit TLS on my ftp, but when I use ftps://mydomain.com it doesn't go to my server.
All I want to know is which link do I have to use to make sure my ftp password is secure?
Thank you
This is an awesome problem you have made :1st_place_medal: :100:

**Comment by alexandre1985** [comment]
Sorry for writing problem instead of program... I meant program, the ftp-srv. It's top :+1: very happy with it

**Comment by alexandre1985** [comment]
I'm using a file browser to access my ftp server.
Which link should I use to make use of explicit tls?
If I use `ftp://mydomain.com` in my file browser is that gonna use explicit tls for the connection?

**Comment by trs** [comment]
The `ftps` "protocol" was just used to differentiate between explicit and implicit TLS with ftp-srv. It's not actually a real protocol.

I don't know about accessing an FTP server via a webbrowser, you'd have to look up documentation for that server, but you'd most likely still use `ftp://...`.

But if ftp-srv is setup using `ftps`, meaning it ONLY accepts TLS connections, then any working connection should be using TLS.
