### ISSUE TITLE
`TypeError: FtpSrv is not a constructor` error when requiring FileSystem

### ISSUE THREAD

**Issue by yungjames** [trs/ftp-srv#52]
Noticed this with the new version I installed today. (2.13.1) . The previous version I was using was 2.11.4.

This works:
```javascript
const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv(config.get('ftp').url, config.get('ftp').options);
```

This throws the following error:
```javascript
const { FtpSrv, FileSystem } = require('ftp-srv');
const ftpServer = new FtpSrv(config.get('ftp').url, config.get('ftp').options);
```
```
const ftpServer = new FtpSrv(config.get('ftp').url, config.get('ftp').options);
                  ^
TypeError: FtpSrv is not a constructor
```

I also noticed in the README there are a few places where `FtpSrv` is referenced as `FtpSvr`.

Looks like `ftp-srv.js` is now missing when npm installed, and the package.json `main` points to `src/index.js`. `ftp-srv.js` is missing from the `files` array in the package.json.  If I put `ftp-srv.js` back manually (I grabbed the one from 2.11.4) and change the package.json to point to it, it works again. I am sure the `main` value was changed for a reason, but not knowing exactly why, I am hesitant to put in a PR that in essence undoes the recent changes.

**Comment by trs** [comment]
Great catch!

I'm very sorry about that. This was caused when upgrading with the `confit` generator.
It automatically changed the package's `main` file, and I failed to notice.

https://github.com/trs/ftp-srv/pull/53

**Comment by yungjames** [comment]
Thank you so much for the super fast turnaround on this!
