### ISSUE TITLE
Invalid response when stat on a file

### ISSUE THREAD

**Issue by JbIPS** [trs/ftp-srv#60]
Hi,

When calling `STAT` on a file, I get a response with an incorrect format: a number then a space then the stat infos.

I first thought it was a client problem (see https://github.com/sergi/parse-listing/issues/13) but it looks like the protocol standard align with the client. 

I think something's wrong here https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stat.js#L31 but I don't know what nor why.

Could you lead me to a solution? Thanks

**Comment by trs** [comment]
Great catch! Thanks for the issue!
I was incorrectly sending only the file data on a `STAT` of a file.

This should be remedied with https://github.com/trs/ftp-srv/pull/61

**Comment by JbIPS** [comment]
Just tried it again, works perfectly 👍 !

Thank you for the fix and this cool project!

**Comment by lexoyo** [comment]
Thank you for the users of @JbIPS 's [unifile project](https://github.com/silexlabs/unifile/)
