### ISSUE TITLE
How close ftp server

### ISSUE THREAD

**Issue by voxsoftware** [trs/ftp-srv#65]
Ftp Server have a listen method, but what about close? I cannot see in documentation a close method

**Comment by trs** [comment]
Sorry the docs are a little lacking!

You can close the docs with the [close method](https://github.com/trs/ftp-srv/blob/master/src/index.js#L138) on the instance of the server.

```js
const FtpSrv = require('ftp-srv');

const ftpServer = new FtpSrv('ftp://0.0.0.0:9876', { options ... });

ftpServer.close();
```

You can also call [quit](https://github.com/trs/ftp-srv/blob/master/src/index.js#L133), which will close and then end the process.
