### ISSUE TITLE
A way to detect when a file upload completes

### ISSUE THREAD

**Issue by mredbishop** [trs/ftp-srv#69]
I may be missing the point entirely or not reading the docs correctly, but I don't see a way to do this?

Cheers,

Ed

**Comment by trs** [comment]
The stream provided by the file system will emit the `close` event when completed (https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L34). Really this is only useful if using a custom file system.

Perhaps a server event would be a good place to add this?

**Comment by mredbishop** [comment]
I guess I could write a wrapper around fs but that seems like overkill?

**Comment by trs** [comment]
@mredbishop I've started work over on this branch: https://github.com/trs/ftp-srv/tree/emit-custom-events

Let me know what you think, feel free to contribute!

**Comment by mredbishop** [comment]
That's awesome! I'll take a look this afternoon and help if I can.

Ed

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/releases/tag/v2.16.0

**Comment by activewolf89** [comment]
Is there a way to know when the FTP connection closes? not when the stream is finishing writing, but when the connection object gets a disconnect -- the opposite of login, such as close

**Comment by trs** [comment]
You could listen to the `close` or `end` event on the [connection's `commandSocket`](https://github.com/trs/ftp-srv/commit/b07e018#diff-875da84119066ec244742e95d1209f0cR34), it's just an instance of n[ode's net socket](https://nodejs.org/api/net.html#net_event_close_1).

Having a `close` event on the connection class would be a great addition.

**Comment by activewolf89** [comment]
Thank you that did the trick-- took me way longer than needed to solve this
