### ISSUE TITLE
Getting users IP address

### ISSUE THREAD

**Issue by SuddenlyH2O** [trs/ftp-srv#73]
Is there anyway to get the IP address of the user attempting to login?
Thanks 😄

**Comment by trs** [comment]
You should be able to use the [ip get method](https://github.com/trs/ftp-srv/blob/master/src/connection.js#L44) on the `connection` object.

```js
ftpServer.on('login', ({connection}, resolve, reject) => {
  console.log(connection.ip);
});
```

**Comment by SuddenlyH2O** [comment]
Oh didn't realize it was that easy.
Thanks.
