### ISSUE TITLE
STOR events not happening for me

### ISSUE THREAD

**Issue by JackCarttronics** [trs/ftp-srv#74]
Is this a bug? Am I doing something wrong here?

The "this.emit('STOR', null, fileName)" line at store.js:46 is called but it never gets to my code.  The file is uploaded.

```
  const ftpServer = new FtpSvr(

    'ftp://' + ip.address().toString() + ':3000', {
      anonymous: false,
      pasv_range: '8000-9000',
      greeting: 'xxx-FTP'
    }
  );

```
```
  ftpServer
    .listen()
    .then(() => {
      gc.log(`started FTP service ${ip.address().toString()}`);
    });

```
```
  ftpServer
    .on('login', ({
      connection, // eslint-disable-line no-unused-vars
      username, password }, resolve, reject) => {

      if (username === 'xxx' && password === 'xxxxx') 
        resolve({ root: './data/'});  
      else  
        reject({ root: './data/anonymous' });
    });

  ftpServer.on('STOR', (error, fileName) => { 
    if (error) console.log(error);
    else console.log(fileName);
  });`
`
```

**Comment by branai** [comment]
I'm having the same problem. It doesn't even happen for a bare-bones setup like this:
`const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv(ip.address().toString()+':9876');
var fs = require('fs');
ftpServer.on('login', (data, resolve, reject) => {
  resolve({root:'public/'})
});
ftpServer.listen();
ftpServer.on('STOR', (error, fileName) => {
  console.log("hit");
});`

**Comment by branai** [comment]
I'm having the same problem. For me, STOR doesn't even happen with a bare-bones setup like this:
`const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv(ip.address().toString()+':9876');
var fs = require('fs');
ftpServer.on('login', (data, resolve, reject) => {
  resolve({root:'public/'})
});
ftpServer.listen();
ftpServer.on('STOR', (error, fileName) => {
  console.log("hit");
});`

**Comment by branai** [comment]
> `const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv(ip.address().toString()+':9876');
var fs = require('fs');
ftpServer.on('login', (data, resolve, reject) => {
  resolve({root:'public/'})
});
ftpServer.listen();
ftpServer.on('STOR', (error, fileName) => {
  console.log("hit");
});`

**Comment by branai** [comment]
I'm having the same problem. For me, STOR doesn't even work for a bare-bones setup like this:
```
const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv(ip.address().toString()+':9876');
var fs = require('fs');
ftpServer.on('login', (data, resolve, reject) => {
  resolve({root:'public/'})
});
ftpServer.listen();
ftpServer.on('STOR', (error, fileName) => {
  console.log("hit");
});
```
"hit" is never printed.

**Comment by trs** [comment]
These events are actually emitted on the connection itself, not the server.

```
ftpServer.on('login', ({connection}) => {
  connection.on('STOR', (error, fileName) => {
    // ...
  });
});
```

I decided to go this way since it's a connection specific action that's happening.

Do you think it would make more sense for all events to be emitted on the server itself?

**Comment by JackCarttronics** [comment]
Thanks for the update.  I understand the logic of different events for different connections.  A chain of .on's that passed the connection would work as well.

**Comment by trs** [comment]
Is this resolved for you then?

**Comment by trs** [comment]
This should be resolved by listening to the client for these events, as apposed to the server.
Feel free to comment if you're still having issues.
