### ISSUE TITLE
Always have "Not a valid directory" error

### ISSUE THREAD

**Issue by siffreinsg** [trs/ftp-srv#78]
When I try to do actions on the ftp server, I always get an error in the console from fs.

Here's the error (I replaced sensitive data with HIDDEN):
> {"name":"ftp-srv","hostname":"HIDDEN","pid":7824,"id":"c9371611-e73c-4b70-a42b-1745957d6418","directive":"CWD","level":50,"err":{"message":"Not a valid directory","name":"FileSystemError","stack":"FileSystemError: Not a valid directory\n    at fs.statAsync.tap.stat (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\ftp-srv\\2.16.1\\node_modules\\ftp-srv\\src\\fs.js:58:38)\n    at PassThroughHandlerContext.finallyHandler (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\promise.js:512:31)\n    at Promise._settlePromise (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\promise.js:569:18)\n    at Promise._settlePromise0 (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\promise.js:614:10)\n    at Promise._settlePromises (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\promise.js:693:18)\n    at Promise._fulfill (C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\promise.js:638:18)\n    at C:\\HIDDEN\\ftpserver\\node_modules\\.registry.npmjs.org\\bluebird\\3.5.1\\node_modules\\bluebird\\js\\release\\nodeback.js:42:21\n    at FSReqWrap.oncomplete (fs.js:171:5)","code":400},"msg":"Not a valid directory","time":"2018-04-23T17:43:13.827Z","v":0}

Here's my code:
```javascript
require('dotenv').load()
const ftpsrv = require('ftp-srv'),
    fs = require('fs')

const server = new ftpsrv(`ftp://127.0.0.1:${process.env.PORT || 7777}`)
server.on('login', (user, resolve, reject) => {
    if (user.username === 'siffrein' && user.password === 'HIDDEN') {
        resolve({ root: process.cwd() + '/public/' })
    } else reject('Bad username or password.')
})
server.listen()
```

The error occurs when I connect, when I manipulate files, ...
I'm on Windows 10 build 1803 with pnpm 1.40.2, npm 5.6.0, node 9.11.2 and the latest WinSCP. I tried with both pnpm and npm.
I had problems at first with node-gyp and dtrace-provider.

**Comment by siffreinsg** [comment]
The output is correct and actually I'm able to see files in my FTP client. But every action still returns errors

**Comment by trs** [comment]
`Not a valid directory` is thrown in [chdir](https://github.com/trs/ftp-srv/blob/master/src/fs.js#L58).

I think this might have to do with the [`_resolvePath`](https://github.com/trs/ftp-srv/blob/master/src/fs.js#L15) function. It might not play well with windows.

**Comment by trs** [comment]
I think [this PR](https://github.com/trs/ftp-srv/pull/88) might solve your issues. It's giving me better path results on my windows machine.
