### ISSUE TITLE
Setting root dir from js code

### ISSUE THREAD

**Issue by inf3rno** [trs/ftp-srv#97]
Is there a way for setting the root dir using js code? There is nothing in the documentation about this, and it appears to use to current working directory instead of the directory I set, when I start the server with node this way:

```
const FtpSrv = require('ftp-srv');
const path = require("path");
const root = path.join(__dirname, "ftp");
const ftpServer = new FtpSrv('ftp://0.0.0.0:9876', {root: root, anonymous: true});
ftpServer.listen();
```

**Comment by inf3rno** [comment]
Another problem that I cannot connect to the server from virtualbox using IE6:
![ftpxxx error ie6](https://user-images.githubusercontent.com/408911/41702853-d295ed00-7531-11e8-9f98-572834405bf7.png)

**Comment by inf3rno** [comment]
I guess this latter one is because of active mode and firewall settings.

**Comment by inf3rno** [comment]
Ok, it's better to give up, traverse the files and create HTTP links for them.

**Comment by trs** [comment]
The `root` and `cwd` can be set on login. See: https://github.com/trs/ftp-srv#login
